language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
before_script: chmod +x mvnw
script: ./mvnw clean install -Dmaven.test.skip=true
notifications:
  email: false
  slack:
    secure: JxArv/LEfNJiiZpyYRMOSGjgEMrI5s5GW0UOESdbtqRpwCJoEqTRFAsSUthuGY6t7ovKRT8TU8XiE2BbIJmb8gK+kTGbtvzxjoTsiWGEJ409+07uZrZkZx/UY0xxQCm+2jl6Az/GZhCxGLpvSHfcjhTZQqFYvKCZVKDyZL+gfyPOxSquqwqiDHO7pwILpN2mqIE9M1IVE346RqlunNI3mBf+PfNc9jBQgHaj+4LTLgXqnOokwHXURET+a6I7W1y2/gmkQqJP22KLolvv7oYxQQjYzM5FlNWejoF0aeLLck+Gmd0vnin0Z7p6S96z8oARki+wBF6dHTDIf6Y2tumh5M/qC0X8Ezuw2Ma7rwQxEhfs3jKuDUbnF5/ly/Jv8beYM5ql9LiEdvhI3kiRsns3EvmYdkYBnU0JU1lfNY49d17d/ChcdFNw93UQkhPZgPRo+qMytJyCVRBgEvT2HMQ0CQX41EBSSNHn2H1VgZp7xc4HTs/nwd0VBYAF+SKpNBzLd7pfNFSClh/hdx9WgXQsD5JKAOydWhshExYizYFYH51isF3GDkPykdTNHp4rl85mSjvpG8dVDwr4xsPUma7ZWTe3sTeraCR83ZDtJSEj71ct6sDILJIVOVM1R5h6eL+Orj2k2PXc9G5Zdu0RjH2bUutKdq1qPpr1UDmd6Jf8Yfw=
